//! Shader generation: `ColorParams` → `narvi.frag` text.
//!
//! Renders the PARAMS block of the reference shader from the active params, leaving the
//! rest of the file (interface, pipeline) intact. Implemented in M1.

use crate::params::ColorParams;

/// Marker lines bounding the regenerated constants block in `shaders/narvi.frag`.
pub const PARAMS_BEGIN: &str =
    "// ──── NARVI PARAMS (regenerated by narvid; keep markers intact) ────";
pub const PARAMS_END: &str = "// ──── END NARVI PARAMS ────";

/// Render the full fragment shader for the given params, ready to write to disk.
pub fn render_shader(_params: &ColorParams) -> String {
    // M1: fill BRIGHTNESS/CONTRAST/GAMMA/SATURATION/VIBRANCE direct, RGB_GAIN from rgb,
    // WHITEBALANCE from kelvin_to_rgb(temperature). Keep markers + interface intact.
    todo!("M1: implement render_shader")
}
