//! Shader generation: `ColorParams` → `narvi.frag` text.
//!
//! Renders the PARAMS block of the reference shader from the active params, leaving the
//! rest of the file (interface, pipeline) intact.

use crate::kelvin::kelvin_to_rgb;
use crate::params::ColorParams;

/// Marker lines bounding the regenerated constants block in `shaders/narvi.frag`.
pub const PARAMS_BEGIN: &str =
    "// ──── NARVI PARAMS (regenerated by narvid; keep markers intact) ────";
pub const PARAMS_END: &str = "// ──── END NARVI PARAMS ────";

/// Reference shader at neutral values. Kept in sync with `shaders/narvi.frag`
/// by a unit test; inlined so the crate is self-contained for crates.io.
pub const TEMPLATE: &str = include_str!("narvi.frag");

fn vec3(v: [f32; 3]) -> String {
    format!("vec3({:?}, {:?}, {:?})", v[0], v[1], v[2])
}

/// Render the full fragment shader for the given params, ready to write to disk.
/// Params are clamped; the PARAMS block markers are preserved.
pub fn render_shader(params: &ColorParams) -> String {
    let p = params.clamped();
    let wb = kelvin_to_rgb(p.temperature);
    let block = format!(
        "{PARAMS_BEGIN}\n\
         const float BRIGHTNESS   = {:?};\n\
         const float CONTRAST     = {:?};\n\
         const vec3  WHITEBALANCE = {}; // {} K\n\
         const float GAMMA        = {:?};\n\
         const vec3  RGB_GAIN     = {};\n\
         const float SATURATION   = {:?};\n\
         const float VIBRANCE     = {:?};\n\
         {PARAMS_END}",
        p.brightness,
        p.contrast,
        vec3(wb),
        p.temperature,
        p.gamma,
        vec3(p.rgb),
        p.saturation,
        p.vibrance,
    );
    // Markers are compile-time constants of TEMPLATE — always present.
    let start = TEMPLATE.find(PARAMS_BEGIN).unwrap_or(0);
    let end = TEMPLATE
        .find(PARAMS_END)
        .map(|i| i + PARAMS_END.len())
        .unwrap_or(TEMPLATE.len());
    format!("{}{}{}", &TEMPLATE[..start], block, &TEMPLATE[end..])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_matches_reference_file() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../shaders/narvi.frag");
        let on_disk = std::fs::read_to_string(path).expect("reference shader");
        assert_eq!(TEMPLATE, on_disk, "src/narvi.frag != shaders/narvi.frag");
    }

    #[test]
    fn neutral_params_are_neutral() {
        let s = render_shader(&ColorParams::default());
        assert!(s.contains("WHITEBALANCE = vec3(1.0, 1.0, 1.0)"));
        assert!(s.contains("VIBRANCE     = 1.0"));
        assert!(s.contains("#version 300 es"));
    }

    #[test]
    fn params_land_in_output() {
        let p = ColorParams {
            vibrance: 1.4,
            temperature: 4000,
            rgb: [1.1, 1.0, 0.9],
            ..Default::default()
        };
        let s = render_shader(&p);
        assert!(s.contains("VIBRANCE     = 1.4"));
        assert!(s.contains("// 4000 K"));
        assert!(s.contains("RGB_GAIN     = vec3(1.1, 1.0, 0.9)"));
        assert!(s.contains(PARAMS_BEGIN) && s.contains(PARAMS_END));
    }

    #[test]
    fn out_of_range_clamps() {
        let p = ColorParams {
            vibrance: 99.0,
            temperature: 50,
            brightness: -3.0,
            ..Default::default()
        };
        let s = render_shader(&p);
        assert!(s.contains("VIBRANCE     = 2.0"));
        assert!(s.contains("// 1000 K"));
        assert!(s.contains("BRIGHTNESS   = 0.5"));
    }

    #[test]
    fn no_forbidden_glsl() {
        // Comments mention the forbidden forms by name; only check code.
        let code: String = render_shader(&ColorParams::default())
            .lines()
            .map(|l| l.split("//").next().unwrap_or(""))
            .collect::<Vec<_>>()
            .join("\n");
        for bad in ["gl_FragColor", "texture2D", "varying", "320 es"] {
            assert!(!code.contains(bad), "generated shader contains `{bad}`");
        }
    }
}
