// Narvi screen shader — Hyprland decoration:screen_shader
//
// This is the REFERENCE shader at neutral values. `narvid` regenerates this file
// on every change by replacing the PARAMS block (between the two marker lines)
// with the active profile's constants, then runs:
//   hyprctl keyword decoration:screen_shader <this file>
//
// Interface is fixed by Hyprland 0.55.x / aquamarine (GLSL ES 1.00 or 3.0 only):
//   - #version 300 es           (NOT 320 es — rejected)
//   - in vec2 v_texcoord        (NOT varying)
//   - out vec4 fragColor        (NOT gl_FragColor)
//   - texture(tex, ...)         (NOT texture2D)
// Pipeline order: brightness -> contrast -> white balance -> gamma -> rgb gain
//                 -> flat saturation -> protective vibrance.

#version 300 es
precision highp float;

in vec2 v_texcoord;
uniform sampler2D tex;
out vec4 fragColor;

// ──── NARVI PARAMS (regenerated by narvid; keep markers intact) ────
const float BRIGHTNESS   = 1.0;          // multiplicative gain (1.0 = neutral)
const float CONTRAST     = 1.0;          // around 0.5 pivot   (1.0 = neutral)
const vec3  WHITEBALANCE = vec3(1.0);    // from temperature (K), computed by narvid
const float GAMMA        = 1.0;          // 1.0 = neutral
const vec3  RGB_GAIN     = vec3(1.0);    // per-channel gain   (1.0 = neutral)
const float SATURATION   = 1.0;          // flat saturation    (1.0 = neutral)
const float VIBRANCE     = 1.0;          // protective vibrance(1.0 = neutral)
// ──── END NARVI PARAMS ────

const vec3 LUMA = vec3(0.2126, 0.7152, 0.0722); // Rec.709

void main() {
    vec4 src = texture(tex, v_texcoord);
    vec3 c = src.rgb;

    // 1. brightness
    c *= BRIGHTNESS;

    // 2. contrast (pivot at mid-gray)
    c = (c - 0.5) * CONTRAST + 0.5;

    // 3. temperature / white balance
    c *= WHITEBALANCE;

    // 4. gamma (guard against negatives from prior steps)
    c = pow(max(c, 0.0), vec3(1.0 / GAMMA));

    // 5. per-channel gain
    c *= RGB_GAIN;

    // 6a. flat saturation
    float luma = dot(c, LUMA);
    c = mix(vec3(luma), c, SATURATION);

    // 6b. protective vibrance: boost muted colors, spare already-saturated + skin
    luma = dot(c, LUMA);
    float mx = max(c.r, max(c.g, c.b));
    float mn = min(c.r, min(c.g, c.b));
    float sat = mx - mn;                                   // 0 = gray, ~1 = vivid
    float boost = (VIBRANCE - 1.0) * (1.0 - smoothstep(0.0, 1.0, sat));
    boost *= mix(1.0, 0.5, step(max(c.g, c.b), c.r));      // damp when red dominates
    c = mix(vec3(luma), c, 1.0 + boost);

    fragColor = vec4(clamp(c, 0.0, 1.0), src.a);
}
